#!/bin/bash
set -e

asList=(
    714     # Apple
    20940   # AKAMAI
    32787   # AKAMAI (other)
    16625   # AKAMAI (other #2)
    57976   # Blizzard
    13335   # CLOUDFLARE
    19679   # Dropbox
    32934   # Facebook
    15169   # Google
    36040   # YOUTUBE - Google Inc., US
    8075    # Micro$oft
    2906    # Netflix
    36692   # OpenDNS
    8403    # Spotify
    46489   # Twitch
    13414   # Twitter
    32590   # Valve
    43821   # WIKIMEDIA-EU
    14907   # WIKIMEDIA-USA
    10310   # Yahoo
    8302    # Zattoo
    64475   # FFFFM
)

IPSET=/sbin/ipset

# Ipsets to add
ipsets=(exit exit6)
# Grep parameter for ipsets
grepCmd=('-v :' ':')


# Add ipset if not exists
ipsetCreate() {
    local name=${1}
    local type=${2-""}

    $IPSET create -exist "${name}" hash:net family "inet${type}" hashsize 2048 maxelem 65536
}

# Add ip ranges to ipset
ipsetAdd() {
    local ipset=${1}

    while read; do
        $IPSET add -exist "${ipset}" "${REPLY}"
    done
}


# Make sure that all ipsets exists
ipsetCreate exit
ipsetCreate exit-temp
ipsetCreate exit6 6
ipsetCreate exit-temp 6

# Clear temp ipsets
for ((i=0; i<${#ipsets[@]}; i++)); do
    $IPSET flush "${ipsets[i]}-temp"
done

# Add as ips to ipsets
for as in "${asList[@]}"; do
    # Get IPs
    asData=$(curl -s "https://stat.ripe.net/data/announced-prefixes/data.json?min_peers_seeing=0&resource=${as}"|jq --raw-output .data.prefixes[].prefix)

    if [[ -n "$asData" ]]; then
        for ((i=0;i<${#ipsets[@]};i++)); do
            # Add IPs to ipset
            ipsetAdd "${ipsets[i]}-temp" < <(echo "${asData}" | grep ${grepCmd[i]})
        done
    fi
done

# Apply and cleanup
for ((i=0; i<${#ipsets[@]}; i++)); do
    $IPSET swap "${ipsets[i]}" "${ipsets[i]}-temp"
    $IPSET flush "${ipsets[i]}-temp"
done

